Make `viw` fail more gracefully

diff --git a/shell_scripts/viw b/shell_scripts/viw
--- a/shell_scripts/viw
+++ b/shell_scripts/viw
@@ -1,1 +1,7 @@
-vi "$(which $1)"
+path=$(which $1)
+returncode="$?"
+if [ "$returncode" -ne 0 ]; then
+    echo "$1": command not found
+    exit $returncode
+fi
+vi $path
